package com.superplanner.app.domain.planning

import com.superplanner.app.domain.model.ActivityInstance
import com.superplanner.app.domain.model.ActivityInstanceId
import com.superplanner.app.domain.model.ActivitySource
import com.superplanner.app.domain.model.Flexibility
import com.superplanner.app.domain.model.NextActionContext
import com.superplanner.app.domain.model.TaskId
import com.superplanner.app.domain.model.TimeRange
import com.superplanner.app.domain.usecase.GenerateDailySchedule
import com.superplanner.app.domain.usecase.RescheduleAfterDelay
import java.time.Instant
import java.time.ZoneOffset
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class DefaultPlanningEngineTest {
    private val start = Instant.parse("2026-09-13T09:00:00Z")

    private val engine = DefaultPlanningEngine(
        generateDailySchedule = GenerateDailySchedule(),
        rescheduleAfterDelay = RescheduleAfterDelay(GenerateDailySchedule()),
    )

    @Test
    fun `production engine returns the route generated by scheduling rules`() {
        val later = activity("later", "10:00", "11:00")
        val earlier = activity("earlier", "09:00", "10:00")

        val result = engine(
            PlanningInput(
                activities = listOf(later, earlier),
                context = NextActionContext(now = start, zoneId = ZoneOffset.UTC),
            ),
        )

        assertEquals(listOf("earlier", "later"), result.route.map { it.activity.id.value })
        assertTrue(result.decisions.all { it.outcome == PlanningDecisionOutcome.SCHEDULED })
    }

    @Test
    fun `production engine exposes unscheduled conflicts instead of hiding them`() {
        val first = activity("first", "09:00", "11:00", Flexibility.FIXED)
        val second = activity("second", "10:00", "11:00", Flexibility.FIXED)

        val result = engine(
            PlanningInput(
                activities = listOf(first, second),
                context = NextActionContext(now = start, zoneId = ZoneOffset.UTC),
            ),
        )

        assertEquals(listOf("first", "second"), result.route.map { it.activity.id.value })
        assertEquals(1, result.unscheduled.size)
        assertEquals(PlanningReason.REQUIRED_CONFLICT, result.unscheduled.single().reasons.single())
    }

    private fun activity(
        id: String,
        startTime: String,
        endTime: String,
        flexibility: Flexibility = Flexibility.FLEXIBLE,
    ) = ActivityInstance(
        id = ActivityInstanceId(id),
        source = ActivitySource.FromTask(TaskId("task-$id")),
        flexibility = flexibility,
        planned = TimeRange(
            Instant.parse("2026-09-13T$startTime:00Z"),
            Instant.parse("2026-09-13T$endTime:00Z"),
        ),
    )
}
